### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#1]
New repo 🎉!

Initial thoughts are to get a discussion going here to get a rough plan for an initial MVP before writing up some issues for more specific areas of discussion?

To make sure we all get on the same page, the basic plan as I understand it:

- Back-end dgraph database
- Implement MVP based on specification doc diagram (see below)
- Map existing UDC data to graph
- Backwards compatible RESTful API for accessing data via existing mSupply instances
- Update graph with additional data, e.g. external codes.
- RESTful API/graphql service for accessing updated data
- Update mSupply to use new API/graph functionality

At the moment I'm thinking a good template moving forward might be to expand each of these points into their own discussion issue? Might help us break the tasks down into actionable issues and divide up some of the tasks?

@mark-prins @katherine-sussol Anything missing? Thoughts?

**Comment by wlthomson** [comment]
Specification doc diagram (see description):

![unified-codes-diagram](https://user-images.githubusercontent.com/43223637/84711593-d1fcb980-afba-11ea-8c6b-a735f7f96200.png)

**Comment by katherine-sussol** [comment]
Sounds like a good starting point to me!

Thinking it might also be good to also have separate items (issues?) for the less 'critical' items (i.e may not be required for basic prototype that we initially build out but things still likely needed and worth discussing) so we don't forget about them later down the line (or when designing/building out other areas). And then maybe if there's a way to tag or prioritise them so we focus on the more critical stuff first (not sure how to do this in GitHub yet), but can still add things if we think of them while we're working on the important stuff.

Some that came to mind were: 
- Basic web UI for Universal Codes (general and admin area)
- Authentication mechanism for API(graph only - assuming we don't need to expose any update ability via REST)/UI (assuming we don't want randoms submitting create/update/delete requests through either channel)
- mSupply pricing export/import mechanism

**Comment by mark-prins** [comment]
yup, great points both of you!
The drug interactions may have to be a separate item of work as well - because it is important, and a reasonable amount of work in mSupply.

**Comment by wlthomson** [comment]
Have made an epic for discussion on the initial prototype [here](https://github.com/openmsupply/unified-codes/issues/2).

Can keep this issue open as a reference for discussing other bits and pieces which might not fit neatly into the prototype. Re. web UI, I'm thinking this might be a bit outside of initial scope? Once we have a prototype up and going and have an idea of how best to structure the data, I think then could move onto discussing the UI aspect?

**Comment by wlthomson** [comment]
Going to go ahead and close this, but feel free to reopen if you think there's still something to be resolved here! 

@mark-prins @katherine-sussol
