### ISSUE TITLE
Product search fails with less than 3 chars in search term

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/unified-codes#108]
## Expected Behaviour

User should be able to search via legacy API for a product by name with less than 3 chars in the search term.

Example:
`GET {RESTHost}/items?name=Am`
should return all results beginning with Am (e.g. Amoxicillin oral capsule, 250mg)

## Current Behaviour

Request times out, with the following error logged (originating from Dgraph):
`APIError: : regular expression is too wide-ranging and can't be executed efficiently
`

## Possible Solution

Random thoughts here, don't necessarily think any of these are ideal 😿 
- Block requests with less than 3 chars (return bad request in API layer)
- Only allow full-term searches
- Spam Dgraph with requests - one for each possible char filled in as the 3rd char...
- ... 

## Steps to Reproduce (bugs only, delete if not applicable)

1. Run legacy api locally (setup by default at localhost:3000)
2. Browse to localhost:3000/items?name=Am
3. Observe the lack of results

**Comment by wlthomson** [comment]
Seems like a pretty significant limitation! Is there a dgraph issue for this?

**Comment by katherine-sussol** [comment]
There are a couple of people with similar queries, the discussions all kind of fizzled (I've just created an account and will post an issue in the forum out of curiosity):
- https://discuss.dgraph.io/t/error-regular-expression-is-too-wide-ranging-and-cant-be-executed-efficiently/3682
- https://discuss.dgraph.io/t/using-regex-function-trigram-index-on-sets-lists/1871

Also done a bit of experimenting, I think for the legacy API we might be ok to do the original query function on type="unit_of_use" and then specify the regex as a filter afterwards (and add a new test case to the test suite! 😀 ).
