### ISSUE TITLE
Create footer component

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/unified-codes#153]
Create a footer, apply style as per inVision

## Expected Behaviour
Actually, the inVision version has the UC logo in the footer and the mSupply foundation logo nowhere.

I suggest something like this:

![footer](https://user-images.githubusercontent.com/9192912/91123391-d9de8580-e6f0-11ea-9630-30287dfab98d.png)

**Comment by wlthomson** [comment]
Just for reference, might be good to include a `jpg` of the footer design under expected behaviour?
