### ISSUE TITLE
Add filter to explorer request

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/unified-codes#170]
The search/filter in the explorer currently filters results shown in the table.
This needs to be wired up to the data-service query now that pagination is available.

## Expected Behaviour
Filtering should filter _all_ results not just the results currently in the table.

**Comment by wlthomson** [comment]
@mark-prins I didn't want to change the capitalisation, really... my brain made me do it! 

![crazy](https://user-images.githubusercontent.com/43223637/92461885-e220df80-f21d-11ea-8901-d3e57044f3ec.gif)

![hippo_oath](https://user-images.githubusercontent.com/43223637/92461890-e4833980-f21d-11ea-8f73-b1865e1dbd08.gif)

**Comment by wlthomson** [comment]
@mark-prins I didn't want to change the capitalisation, really... my brain made me do it! 

![crazy](https://user-images.githubusercontent.com/43223637/92461885-e220df80-f21d-11ea-8901-d3e57044f3ec.gif)

**Comment by mark-prins** [comment]
@wlthomson your pedantry is noted. ( and appreciated )

**Comment by wlthomson** [comment]
@mark-prins I think we may want to pause on this until we figure out the front-end/back-end architecture steps. I think for now, it may be a good idea to get everything wired up working locally (including filtering, even though I know it's stupid to do it front-end), before moving forward. I think it might be a good idea to get the pagination AND searching functionality working locally (even if badly optimised), before moving forward with refactoring them both at the same time.

**Comment by wlthomson** [comment]
@mark-prins Just realised, I've arrived too late. Will review PR and then we can think of next steps!
