### ISSUE TITLE
Data service schema mandatory fields

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#171]
While reviewing #169, noticed a possible discrepancy with some of the predicates for the `Entity` type.

## Expected Behaviour

`Entity` type should have mandatory `code` (and `type`?), and optional description.

```
type Entity {
  code: String!
  description: String
  has_property: [Property]
  has_child: [Entity]
  type: String
}
```

## Current Behaviour

`Entity` type has mandatory `type` and `description`, and optional `code`:

```
type Entity {
  type: String!
  code: String
  description: String!
  has_property: [Property]
  has_child: [Entity]
}
```

## Possible Solution

Update the schema? 

Note: if others are in agreement, I think it would be nice to also have a simple convention for schemas, whereby predicates are listed alphabetically (might just simply things)? If so, could possibly piggyback that into this.

🐷  (piggyback request): can we remove the `code` search as part of this please? ( refer to #172 )
🐷  (piggyback request): make orderBy and offset / first mandatory, or perhaps default those that make sense to default. ( reference: https://github.com/openmsupply/unified-codes/pull/178#discussion_r488305353 )
🐷  (piggyback request): Confirm DetailEntityListItem key is unique https://github.com/openmsupply/unified-codes/pull/249#discussion_r508075613

**Comment by wlthomson** [comment]
@katherine-sussol @mark-prins Not sure if this is me missing something, so marking this as a discussion/question rather than bug for now!

**Comment by mark-prins** [comment]
Yes! alphabetical makes me happy. Agree with the mandatoryness too. Noticed that and thought to change but haven't yet.
![](https://media1.giphy.com/media/13G7hmmFr9yuxG/giphy.gif)

**Comment by katherine-sussol** [comment]
Agree with both alphabeticalling and mandatorying! I think I tried to make code mandatory once but ran into validation issues as the current migrated data has some entities without codes (and also wasn't sure if it was truly mandatory and didn't want to dig too deep) - in particular, things like form entities, should it be possible to create lots of { type: form, description: injection } nodes with different codes (currently they're different nodes but with no code)? Or should all injections inherit from the same node? Graph wise I think it makes sense to refer to the same node? 

Either way (and sorry if I'm being confusing) I think some data massaging may be required 💆

**Comment by mark-prins** [comment]
@katherine-sussol oh, yes - blank `code` would be a problem!
I've checked the current data set ( on [google drive](https://drive.google.com/open?id=180OBUKH7GavVzAWinNOhPpnGmbJOHRUg&authuser=m2%40msupply.foundation&usp=drive_fs) ) and that is looking good - there was some reworking of the data migration which I think happened after the schema was done.

**Comment by katherine-sussol** [comment]
Right - from that data set it looks like we have all the `unit_of_use` entities covered 😁  - I'm still unsure about the `form_category` and `form` nodes. 

Maybe an example of some of the nodes in Dgraph at the moment might help illustrate the source of my uncertainty (when querying for all nodes of type 'form' - note they have no codes at the moment):
```
      {
        "description": "tablet, dispersible",
        "type": "form"
      },
      {
        "description": "tablet",
        "type": "form"
      },
      {
        "description": "tablet",
        "type": "form"
      },
```
Do we:
a) Make them not entities anymore (e.g. we create a new type that doesn't need a code) - this breaks the current recursive hierarchy though
b) Keep it as is and just give them all unique codes
c) Merge all duplicates into a single node and assign it a code (would need some node repointing but I think is more graph-appropriate?)
d) None of the above - these are ridiculous suggestions 🙀

**Comment by mark-prins** [comment]
I like (b) :)
