### ISSUE TITLE
Refactor EntityBrowser props

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#190]
See #187 for discussion.

## Expected Behaviour

- Explicit child props (decompose `childProps` into explicit props).
- Explicit child styles (decompose `classes` into explicit styles).
- Explicit `variables` props (decompose `variables` into `page` and `rowsPerPage`).
- Remove `noResultsMessage`.
- Remove `<>` fragments, maintain consistency of all exported components wrapped in layout components (simplifies styling).

## Current Behaviour

See above.

## Possible Solution

Refactor component definition + props.

**Comment by mark-prins** [comment]
the material grid:containers were not playing nicely, and the code had containers nested in containers which causes weird effects. While I'd like to remove `<>` fragments, doing so will take a fair bit of time. The other changes here won't take long.

**Comment by wlthomson** [comment]
Thanks, will have a look. If it takes any significant time, will leave it for later!
