### ISSUE TITLE
Initial MVP

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#2]
## Description

Epic for initial unified codes MVP.

See child epics:

- RESTful API: #9. 
- Dgraph backend: #11. 

## Initiative / goal

Idea is to get some discussion/planning going by hitting the ground running with a minimal prototype server consistent with initial specification doc diagram provided by @craigdrown:

![unified-codes-diagram](https://user-images.githubusercontent.com/43223637/84711593-d1fcb980-afba-11ea-8c6b-a735f7f96200.png)

Architecture is to be discussed, by my current thinking for what it's worth is to divide the prototype up into two separate services:

- Dgraph database.
  - Server running standalone docker instance.
  - Stores products/properties as graph nodes/relations.
  - CRUD operations exposed via GraphQL mutations/queries.
- REST API.
  - HTTP server.
  - CRUD operations exposed via RESTful API endpoints.
  - Exposes all `v1` endpoints.
  - Endpoints map API calls to mutations/queries on Dgraph server and map Dgraph response to expected API response.

I think doing it this way has a few benefits:

- Decouples the `v1` and `v2` implementations (simpler code, can work in parallel).
- Keeps things open-ended for the main implementation.
- Gives us a good insight into how easy or hard it is to replicate the existing universal codes functionality using Dgraph/graphql.

## Scope

To be discussed.

Some initial thoughts:

- Dockerised Dgraph server.
- Scripts to mutate/query graph database.
- Graph schema consisting of core types for representing entities (e.g. medicinal products) and properties (e.g. dose forms/strengths, external codes).
- Scripts to migrate existing universal codes data to updated schema.
- Scripts to add additional data, e.g. compound drugs.
- Example native graph queries to demonstrate compliance with main product owner requirements.
- Standalone REST API server implementing `v1` endpoints.
- Routing methods for mapping each `v1` endpoint to equivalent graphql query/mutation.

## Team members/stakeholders

- @craigdrown (product owner)
- @mark-prins (team lead)
- @wlthomson (dev)
- @katherine-sussol (dev)

## Timeline

Scope is quite open-ended, so going to set a rough provisional deadline of 30/07. Can bring this forward or push back depending on work loads/progress.

@mark-prins @katherine-sussol Will also need to have a bit of a think about the queries to implement. Idea is to show basic functionality, e.g. looking up drugs by code, traversing down the tree, limiting search by "level", finding products in various pack sizes etc.

**Comment by wlthomson** [comment]
Thinking of a basic schema looking something like:

```
item {
  description: string,
  type: string,
  code: string,
  has_property [uid],
  has_child: [uid],
}

property {
  description: string,
  type: string,
  value: string,
}
```

In the above schema, `has_property` and `has_child` are equivalent to the horizontal and hierarchical relations (respectively) in the given schematic. The type field is useful for representing the level in the hierarchy of a given item and the data represented by a given property (e.g. `item.type` may be `medicinal_product`, `property.type` may be `gs1_code`).

**Comment by wlthomson** [comment]
Update: think this is probably best as an epic! 

Will add links to issues in description.

**Comment by wlthomson** [comment]
Update: description updated, feedback appreciated! 

@mark-prins @katherine-sussol 

I think once we agree on a loose scope for the prototype, we can start making individual issues and get moving!

**Comment by katherine-sussol** [comment]
Mega comment (still working out the best way to structure these)

**Scope**
Think we're on the same page about the scope for the initial prototype, since at this stage the most uncertainty seems to be around the use of Dgraph itself (and the structure/queries associated with it), makes sense not to bloat it out with any additional concerns (e.g. UI). 

I think it would also be good for us to have some sample v1 (via mysql) queries + results against the existing service and compare them to our v1 (via graph) equivalents so we can demonstrate we can backward support sufficiently.

**Architecture**
Regarding the REST api, I'm wondering if it's necessary to add additional endpoints beyond what is already accessible via v1? I can see the appeal of a 'unified' api front (i.e all requests must go through REST - and if we're trying to standardise APIs across projects then maybe this is the right call), but then also thinking it may be an unnecessary additional layer for new requests when we can directly serve data via graph? Unless we're talking about exposing requests via both REST and graph to public? Sounds like it could get confusing...keen to hear thoughts on this (especially if it seems like I'm misinterpreting anything). 

**Schema**
Still digesting proposed schema and overall diagram - will update!

**Comment by mark-prins** [comment]
schema looks good - essentially the same as what I was getting to in this: https://drive.google.com/open?id=1tSA03l-_ho_dTacNaYt2GLMKGk-BIZcb&authuser=m2%40msupply.foundation&usp=drive_fs I think.

is there a reason that `data_type` is dropped from the `property`?

Agree with you @katherine-sussol - I don't think we should be extending the REST API; that one isn't a CRUD, should just be R; we only have to support existing functionality.

**Comment by wlthomson** [comment]
@katherine-sussol @mark-prins Thanks for feedback, agree with everything said!

I think perhaps didn't explain the REST API bit clearly. No suggestion to extend or add additional endpoints, idea is just the implement the existing endpoints. So, correct in saying the existing functionality will be provided by both the REST API and the graph, but any additional functionality will be via the graph, not suggesting "backporting" to the API. 

The reason for the standalone API server is to basically add backwards compatibility without coupling the new implementation to any previous implementation or design decisions. An analogy which maybe is helpful is to think of the standalone REST server as a "translator" which interprets the requests made by mSupply and translates them for the Dgraph server to understand (and translates the Dgraph response for mSupply to understand). So, to be technical, it's more of an API proxy rather than a server, which exposes a subset of the graph queries as REST endpoints (i.e. the `v1` endpoints).

Does that clarify a bit? All on the same page?

**Comment by wlthomson** [comment]
@katherine-sussol @mark-prins Thanks for feedback, agree with everything said!

@katherine-sussol

I think perhaps didn't explain the REST API bit clearly. No suggestion to extend or add additional endpoints, idea is just the implement the existing endpoints. So, correct in saying the existing functionality will be provided by both the REST API and the graph, but any additional functionality will be provided only by the graph, not suggesting "backporting" new queries etc. by implementing new REST endpoints.

The reason for the standalone API server is to basically add backwards compatibility for existing mSupply instances without coupling the new implementation to any previous implementation or design decisions. The sole function of the API server (to be technical, I guess it's more of a proxy) is to provide access to the data stored in the graph via the existing v1 API. An analogy could be to think of the API server as a "translator" which interprets the requests made by mSupply and translates them for the Dgraph server to understand (and translates the Dgraph response for mSupply to understand). The idea is that instead of having to upgrade existing mSupply instances to be compatible with the new unified codes graph API, they can just be pointed to the REST API server. It's just a way of allowing previous mSupply versions to access the new shiny graph data using the good old v1 API.

@mark-prins

Thinking was that data_type could be dropped for initial prototype as couldn't think of a use-case where we need to know the type of a value outside of "aggregation" queries (IIRC we discussed something along these lines in person?)

Does that clarify a bit/get us more on the same page?

**Comment by katherine-sussol** [comment]
@wlthomson Yep, looks like we're on the same page on the overall structure, no confusion there :). Sounds like a good way forward. I think the point that made me specifically question back porting was the note under the REST api heading ('CRUD operations exposed via RESTful API endpoints'), though we can flesh that out in more detail in the subsequent issues we create.

@mark-prins Just double checking - are you referring to a variation on tab v3 of the diagram? (the link is directing me to v1 by default but I'm definitely missing something if that's the case). 
I think I can visualise it working with the proposed schema if my understanding is correct ...

**Comment by wlthomson** [comment]
> ![UC_ApiConceptual](https://user-images.githubusercontent.com/65875762/84963459-90f0da80-b15d-11ea-9b5d-b9853f38ddd7.png)

Awesome! Your design is pretty much exactly how I'm thinking. The only part which may be slightly misleading is the mSupply bit where it has old requests and new requests from the same mSupply instance. The idea (from my perspective, @mark-prins may think differently!) is for the REST API to support backwards compatibility only with existing versions of mSupply. Once we get everything going and start making changes to the mSupply codebase, the idea is that we can transition mSupply from the old API to graphql. So, ideally we would migrate the old API functionality directly to graphql sent from the mSupply instance, so that eventually the RESTful API can be deprecated. 

@katherine-sussol @mark-prins Does that make sense? Agree? Disagree?

**Comment by katherine-sussol** [comment]
Ooh right, I see what you're saying, so if we took that approach there would be a transition period where we have both old mSupply (calling v1 via REST) and new mSupply (querying graph directly) running. If we could get rid of the REST server I'd be happy :) although it makes me wonder how often mSupply clients upgrade (do we have a case of having some clients on really old versions of the software that will never upgrade?). Regardless I think it's probably still good to move in that direction..

This probably also ties in a bit with your comment on #8 - I kind of think that if we went with this approach then it's a stronger case for pushing all new queries through graph rather than REST.

Hopefully I'm making sense 😃

**Comment by mark-prins** [comment]
yes all round! on the same page - thanks!
And yes too - it was the `v3` tab of the diagram that I was intending. I've now created a `v5` and moved it to the front of the tab order - so it should show by default.
This illustrates the schema you've proposed in this issue Will - essentially just renaming things 😺

**Comment by wlthomson** [comment]
Update: 

Deadline for MVP (including API and Dgraph backend) has been set for 31/07/20.

Remaining MVP work will be broken down and scoped into weekly sprints. Team will meet each week to discuss last weeks sprint and organise the upcoming sprint for that week. End goal is to have a fully-functional API which is compatible with existing mSupply instances (and ideally a minimal UI, depending on progress). 

Moneyworks jobs have been updated to correspond with our roadmap, so all progress should be trackable via job sheets.

@katherine-sussol @mark-prins @craigdrown

**Comment by wlthomson** [comment]
@mark-prins @katherine-sussol As discussed, going to go ahead and close this and migrate agreed goals to `v2` release issue.
