### ISSUE TITLE
Data fetch notification timing

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/unified-codes#218]
Issue arising from changes in #201 
When fetching data, the notification isn't dismissed when data is returned.

for example:

![fetching](https://user-images.githubusercontent.com/9192912/95400921-67f09180-0968-11eb-9f59-2a55e6e937be.gif)

**Comment by wlthomson** [comment]
Going to put this in this week's sprint. May get bumped to next week, but should be a pretty quick fix!

**Comment by mark-prins** [comment]
fixed by 1797a0d
