### ISSUE TITLE
Decouple GraphQL schema types from Dgraph

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/unified-codes#219]
Discrepancy uncovered with the changes as part of #201 

Presently the GraphQL schema uses and returns `has_property` and `has_child` fields, however consuming code is using the `IEntity` type, which calls these `properties` and `children`. Some realignment required - this is currently causing a bug with DrugInteractions retrieval (and will also likely impact the `Details` page).

## Possible Solution

Move the GraphQL Schema and resolver logic away from using Dgraph specific type names.
Web queries will need to be updated to use the new names.

**Comment by katherine-sussol** [comment]
I've stolen this one for the sprint - should also be a relatively small one I think

**Comment by wlthomson** [comment]
I suggest something like `IEntity` and `IEntityType` (and can adopt a similar pattern for other types, e.g. `IProperty`). Can then have `Entity implements IEntity & IEntityType`.

**Comment by katherine-sussol** [comment]
Was originally just thinking of renaming the fields in the Apollo schema (to basically match the `IEntity` shape) and when we get the results from Dgraph, to map any `has_property` -> `properties` and any `has_child` -> `children`.

I'm a bit unclear on how to use `IEntityType` in this context, did you mean using that type to represent the Dgraph structure behind the scenes? Let me know if I'm off base here 🤔  I feel like I might have missed your point or some context.

**Comment by mark-prins** [comment]
Thanks @katherine-sussol for spotting this! I was wondering why the interactions is failing now.

Can you also change line 69 in `resolvers.ts` as well? 
```
    if (rxNavIds?.length) {
```
as `rxNavIds` is null when things go wrong, so that blows up. I've added the `?` to help out a little.

**Comment by wlthomson** [comment]
@katherine-sussol  That approach sounds good! The mapping is quite easy to do in the Dgraph query (IIRC, it's something like `has_property: properties`).
