### ISSUE TITLE
Specify source for interactions

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/unified-codes#231]
By default the source of drug interactions is DrugBank - and this will only provide `N/A` as the severity.
It is possible to specify the source and request high severity interactions:
 
`sources=ONCHigh to give just the high severity`

Default to high interactions and allow the requester to specify the source.
Side thought: allow the user to specify severity and behind the scenes select the source? 🤔 
This is more logical for users, though less specific - I don't like the idea that we are hiding options.

## Expected Behaviour
Able to request interactions from a specific source.
Able to retrieve high severity  interactions

## Current Behaviour
All interactions are `N/A` severity. We also return a *lot* of interactions as a result.

**Comment by katherine-sussol** [comment]
Found a few examples from our current dataset that have both ONCHigh and Drugbank results! (for reference/testing)
- Azathioprine 50mg tablet (3723a4bf)
- Azithromycin 250mg capsule (373ad4bf)

Agree that there are a lot though - makes it hard to see 👀

**Comment by DhanyaHerath** [comment]
possibly already done? @katherine-sussol

**Comment by katherine-sussol** [comment]
Yep! Done with #281
