### ISSUE TITLE
Items endpoint failing invalid params test

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/unified-codes#25]
As per screenshot below:
<img width="582" alt="Screen Shot 2020-07-03 at 10 29 57 AM" src="https://user-images.githubusercontent.com/65875762/86414500-2c667b80-bd18-11ea-92fe-8067e8fb7ef0.png">

UPDATE post-fix: 
mapper.js had some minor issues which meant the request would not get blocked:
- request.params is null in function (changed to request.query)
- request.url is null in function (changed to request.raw.url)
- full url with query string wasn't matching key to access PARAMETERS object
- reduce function was returning strange results e.g:
  - items?invalid=data&test=moredata => { valid: [], invalid: { query: 'test' } } 
  - updated to do simple filter of params on whitelist

**Comment by wlthomson** [comment]
@katherine-sussol Could you update the issue with a bit more details now you know the cause? Just useful for posterity!

**Comment by katherine-sussol** [comment]
@wlthomson Done - have updated it with findings discovered while creating PR 😸
