### ISSUE TITLE
Add additional entity types

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#254]
Add interfaces + classes for entity instances.

## Expected Behaviour

Typings to make `EEntityType` more static. Less run-time errors + more self-documenting code.

Proposed changes as of 10/23:

- `Entity`
- `ProductCategory implements Entity`
- `Product implements Entity`
- `FormCategory implement Entity`
- `Form implements Entity`
- `FormQualification implements Entity`
- `FormUnit implements Entity`
- `PackQualification implements Entity`
- `Pack implements Entity`

e.g.

```
interface Entity {
  code: string;
  type: EntityType;
  name: string;
  has_child: Entity[];
  has_property: Property[];
}

interface PropertyCategory implements Entity {
  code: string;
  type: EntityType.PropertyCategory; // Not sure if this is valid ts, but probably some way of doing this!
  name: string;
  has_interaction: Interaction[];
  has_child: Product[]; // Note type constraints enforce hierarchy
  has_property: Property[];
}
```

## Current Behaviour

Entity typing all dynamic.

## Possible Solution

Add subclasses/interfaces, e.g. `IDrugEntity implements IEntity { interactions?: IDrugEntityInteraction[] }`.

**Comment by wlthomson** [comment]
Update:

Proposed schema as of 10/23 has following types:

- `IEntity`
- `IProductCategoryEntity implements IEntity`
- `IProductEntity implements IEntity`
- `IFormCategoryEntity implement IEntity`
- `IFormEntity implements IEntity`
- `IFormQualificationEntity implements IEntity`
- `IUnitEntity implements IEntity`
- `IPackagingEntity implements IEnttiy`
- `IPackEntity implements IEntity`

e.g.

```
interface IEntity {
  code: string;
  type: EEntityType;
  name: string;
  children: IEntity[];
  properties: IProperty[];
}

interface IPropertyCategoryEntity implements IEntity {
  code: string;
  type: EEntityType.PropertyCategory; // Not sure if this is valid ts, but probably some way of doing this!
  name: string;
  children: IProductEntity[]; // Note type constraints enforce hierarchy
  properties: IProperty[];
}

@katherine-sussol @mark-prins Any thoughts?

**Comment by katherine-sussol** [comment]
I like the proposed type updates 👍 . For entities that can have multiple types of children I guess we just need to know in advance which relation types are valid (which I suppose we kind of do now?). And combination drugs will be handled by `IProductEntity` having `IProductEntity` children?

**Comment by wlthomson** [comment]
> I like the proposed type updates 👍 . For entities that can have multiple types of children I guess we just need to know in advance which relation types are valid (which I suppose we kind of do now?).

Yup, exactly! Just adding type safety to what is currently only enforced at the data level (although not enforced atm as we don't have any JSON schema validation... woo new issue!).

> And combination drugs will be handled by `IProductEntity` having `IProductEntity` children?

Ah good point, I think `IProductEntity` will have a specific relation, e.g. `combines`?

**Comment by wlthomson** [comment]
Update:

Proposed schema as of 10/23 with @katherine-sussol feedback and consistent with #257 (note: for simplicity, have omitted details like `I` etc., but these are all interfaces).

- `IEntity`
- `IProductCategory implements Entity`
- `IProduct implements Entity`
- `IFormCategory implement Entity`
- `IForm implements Entity`
- `FormQualification implements Entity`
- `IFormUnit implements Entity`
- `PackQualification implements Entity`
- `Pack implements Entity`

e.g.

```
interface IEntity {
  code: string;
  type: EEntityType;
  name: string;
  has_child: Entity[];
  has_property: Property[];
}

interface IPropertyCategory implements IEntity {
  code: string;
  type: EEntityType.PropertyCategory; // Not sure if this is valid ts, but probably some way of doing this!
  name: string;
  has_interaction: Interaction[];
  has_child: Product[]; // Note type constraints enforce hierarchy
  has_property: Property[];
}

**Comment by katherine-sussol** [comment]
> Ah good point, I think IProductEntity will have a specific relation, e.g. combines? 

Cool `combines` makes more sense imo as it's quite a specific type of relation.

> Can't remember why we went with children and properties instead of has_child and has_property... any reason we shouldn't go with those?

No objective reason, just subjective from both of us I think! (and a desire to keep the dgraph and graphql relations separate?). https://github.com/openmsupply/unified-codes/pull/204#discussion_r496355002

**Comment by wlthomson** [comment]
> > Ah good point, I think IProductEntity will have a specific relation, e.g. combines?
> 
> Cool `combines` makes more sense imo as it's quite a specific type of relation.
> 
> > Can't remember why we went with children and properties instead of has_child and has_property... any reason we shouldn't go with those?
> 
> No objective reason, just subjective from both of us I think! (and a desire to keep the dgraph and graphql relations separate?). [#204 (comment)](https://github.com/openmsupply/unified-codes/pull/204#discussion_r496355002)

Hmm, I suggest for consistency we go with the dgraph style throughout (i.e. `has_X`), as it is a bit clearer in terms of specifying that the relation is an "edge" from one node to another (or many).

**Comment by katherine-sussol** [comment]
> Hmm, I suggest for consistency we go with the dgraph style throughout (i.e. has_X), as it is a bit clearer in terms of specifying that the relation is an "edge" from one node to another (or many).

Yep works for me! Don't feel too strongly either way. I think one is clearer/more explicit from a schema perspective but a little messier to write/query, while the other is nicer in code but not as explicit in the schema 🤷

**Comment by wlthomson** [comment]
Update from #257:

Surprise! Going with plurals instead of `has_x` now.

![surprise](https://user-images.githubusercontent.com/43223637/97156012-fd01e000-17da-11eb-9619-35775ecdb83f.gif)

Also to avoid duplication, see #257 for updated proposed schema.

**Comment by mark-prins** [comment]
we had agreed on `children` and `properties` - so I'm fine with sticking to that.
It means that we don't need to map from `has_X` to plural, which is what the graphQL usage ended up as, since `has_X` only makes sense in a very specific context.

**Comment by katherine-sussol** [comment]
@katherine-sussol Review and check if done

**Comment by katherine-sussol** [comment]
Looks like specific entity types were added against issue https://github.com/openmsupply/unified-codes/issues/257, with PR https://github.com/openmsupply/unified-codes/pull/279
