### ISSUE TITLE
Update graph schema

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#257]
Discussion issue for discussing/documenting data + schema updates.

## Expected Behaviour

Entities:

```
Entity implements IEntity {
  uid: string;
  code: string;
  name: string;
  type: EEntityType | string;
  children: Entity[];
  properties: Property[];
}

CategoryEntity extends Entity implements ICategoryEntity {
  uid: string;
  code: string;
  name: string;
  type: EEntityType.Category;
  children: ProductEntity[];
  properties: CategoryProperty[];
}

ProductEntity extends Entity implements IProductEntity {
  uid: string;
  code: string;
  name: string;
  type: EEntityType.Product;
  combines: ProductEntity[];
  children: RouteEntity[];
  properties: ProductProperty[];
}

RouteEntity extends Entity implements IRouteEntity {
  uid: string;
  code: string;
  name: string;
  type: EEntityType.Route;
  children: FormEntity[];
  properties: RouteProperty[];
}

FormEntity extends Entity implements IFormEntity {
  uid: string;
  code: string;
  name: string;
  type: EEntityType.Form;
  children: (FormQualifierEntity | UnitEntity)[];
  properties: FormProperty[];
}

FormQualifierEntity extends Entity implements IFormQualifierEntity {
  uid: string;
  code: string;
  name: string;
  type: EEntityType.FormQualifier;
  children: UnitEntity[];
  properties: FormQualifierProperty[];
}

UnitEntity extends Entity implements IUnitEntity {
  uid: string;
  code: string;
  name: string;
  type: EEntityType.Unit;
  children: (PackImmediateEntity | PackSizeEntity)[];
  properties: UnitProperty[];
}

PackImmediateEntity extends Entity implements IPackImmediateEntity {
  uid: string;
  code: string;
  name: string;
  type: EEntityType.PackImmediate;
  children: PackSizeEntity[];
  properties: PackImmediateProperty[];
}

PackSizeEntity extends Entity implements IPackSizeEntity {
  uid: string;
  code: string;
  name: string;
  type: EEntityType.PackSize;
  children: (PackOuterEntity | ManufacturerEntity)[];
  properties: PackSizeProperty[];
}

PackOuterEntity extends Entity implements IPackOuterEntity {
  uid: string;
  code: string;
  name: string;
  type: EEntityType.PackOuter;
  children: ManufacturerEntity[];
  properties: PackOuterProperty[];
}

ManufacturerEntity extends Entity implements IManufacturerEntity {
  uid: string;
  code: string;
  name: string;
  type: EEntityType.Manufacturer;
  children: BrandEntity[];
  properties: ManufacturerProperty[];
}

BrandEntity extends Entity implements IBrandEntity {
  uid: string;
  code: string;
  name: string;
  type: EEntityType.Brand;
  children: undefined;
  properties: BrandProperty[];
}
```

Properties:

```
Property {
  type: PropertyType;
  value: object;
}

ProductInteractionProperty extends Property implements IProductInteractionProperty {
  type: PropertyType.ProductInteraction;
  value: {
    name: string;
    description: string;
    severity: string;
    source: string;
    rxcui: string;
  }
}
```

Other:

```
EntityResultSet {
  results: Entity[];
  size: number;
}

PropertyResultSet {
  results: Property[];
  size: number
}

ResultSet = EntityResultSet | PropertyResultSet;

EntityRequest {
  filter: EntityRequestFilter;
  first: number;
  offset: number;
}

EntityRequestFilter {
  code: string;
  name: string;
  orderBy: string;
  orderDesc: bool;
  type: string;
}
```

Notes:

- `Entity` split into explicit types for each level.
- `EntitySortInput` removed (my mistake!).
- `EntityCollection` updated to `EntityResultSet` and polymorphic `ResultSet` added.
- Redundant `Entity` specifiers removed.
- `Entity.description` renamed to `Entity.name`.
- Interactions to be resolved at `ProductEntity` level.
- Interactions to be given dedicated query, remove from entity and entities query.

## Current Behaviour

```
Entity {
  uid: string;
  code: string;
  description: string;
  type: string;
  interactions: DrugInteraction[];
  children: Entity[];
  properties: Property[];
}

EntityCollection {
  data: Entity[];
  totalLength: number;
}


EntitySearchInput {
  code: string;
  description: string;
  orderBy: EntitySort;
  type: string;
}

EntitySortInput {
  field: string;
  descending: boolean;
}

PropertyType {
  type: string;
  value: string;
  properties: Property[];
}

DrugInteractionType {
  name: string;
  description: string;
  severity: string;
  source: string;
  rxcui: string;
}
```

## Possible Solution

- Add `entity` types to `libs/data/src/lib/types/entity`.
- Add `property` types to `libs/data/src/lib/types/property`.
- Update query types + query logic.

**Comment by wlthomson** [comment]
Update from meeting today (@wlthomson, @craigdrown, Rowena, Emily).

- Agreement on graph schema w/ 8 levels (level and top node descriptors, e.g. "Root" and "Medicine", may be substituted with a better description if we think of one!):
  - Root ("Medicine", "Consumable", "Other").
  - Medicinal product (e.g. "Amoxicillin").
  - Mode of administration (e.g. "Oral").
  - Dose form (e.g. "Tablet").
  - Dose qualification (e.g. "Dispersible") .
  - Strength/unit (e.g.  "100mg/5ml").
  - Immediate packaging (e.g. "ampoule"). 
  - Pack size (e.g. "100").
- Some levels are optional ("Dose qualification", "Immediate packaging"), meaning some nodes at the same level may have more parents than their siblings (think this will be an important consideration re. depth limits on recursive queries).
- Current top-level descriptors should be updated to avoid confusion (i.e. "Drug" -> "Medicine", "Medicinal product" -> "Consumable").
- All nodes should have universal codes (e.g. `Amoxicillin`, `Amoxicillin - Oral`, `Amoxicillin - Oral tablet` etc. should all have unique UIDs).

@mark-prins @katherine-sussol Questions + comments if you have them!

**Comment by wlthomson** [comment]
A few additional thoughts for feedback:

- Existing schema + types are based on generic `IEntity` and `IProperty` types. Should we consider adding more type data as described in #254? Would be useful to have e.g. `IRootEntity` and constrain `children` to only nodes of `IMedicinalProductEntity` etc. Main motivation is documentation... I think having typings would make the schema a fair bit more self-documenting?
- Still not too sure how we are going to deal with non-medicine types, e.g. consumable. Take example of a syringe; many of the levels are not applicable. Going back to previous, it might be an idea to define typings such that each level can have children of any level below it. That way, we get a good balance of flexibility and type constraints (basically a tree invariant which allows for levels to be "skipped")?

**Comment by katherine-sussol** [comment]
Just wanting to check - is this the Dgraph schema or the GQL one? (they are both graphs 🙀  - unless we mean to consolidate the two? e.g. Interactions is currently part of GQL but Dgraph knows nothing about them)

I like the overall structure, though have also been thinking...as soon as 4.14 is released does that mean we have to keep a version of the old gql api up and running? With this new schema, the current 4.14 mSupply client isn't going to be able to understand the new query structure?

**Comment by mark-prins** [comment]
Some notes:

- children & properties & interactions ( rather than has_ )
- extend REST endpoint to allow mSupply some separation from graphQL schema changes
- change description to name
- update mSupply to use REST rather than graphQL
- note the difference between graphQL and dgraph schemas
- aliases / synonyms using @tags

**Comment by wlthomson** [comment]
@mark-prins Thanks for the notes! Some of these are covered by this issue, but will make new issues for:

- Extend `legacy-api` with `v3` REST endpoints.
- Add synonyms using tags.

**Comment by wlthomson** [comment]
Updated proposed changes with feedback from meeting + email thread:

- Entity types updated (no change to actual hierarchy/relationships).
- All `entity.description` renamed to `entity.name`.
- All relationships renamed to use plural nouns, e.g. `entity.has_child` renamed to `entity.children`.

**Comment by wlthomson** [comment]
Updated proposed changes with feedback from discussion with Rowena + @mark-prins:

- Interactions to be resolved at `ProductEntity` level. 
- Interactions to be given dedicated query, remove from `entity` and `entities` query.

Have updated description with latest schema 🎉 .
