### ISSUE TITLE
Can't copy the code of an item

### ISSUE THREAD

**Issue by craigdrown** [openmsupply/unified-codes#304]
In the web interface there's no way to copy a code - all this looking up of codes and no way other than transcribing to actually grab one (apart from the API of course ;-)  )

**Comment by craigdrown** [comment]
ahem - I didn't assign all 3 of you - some template magic I expect ;-)

**Comment by katherine-sussol** [comment]
Just passing through and double-checking after having a look at the interface - it looks like the codes are copy-able/select-able on the details page, is this more about being able to copy a code on the list page directly (maybe by selecting the code column?) without having to open a specific product? 

e.g. of Details Code
![image](https://user-images.githubusercontent.com/65875762/100300876-cf879c80-2ffb-11eb-92cd-5b83040636e4.png)

**Comment by wlthomson** [comment]
Could add a little clickable copy icon next to the code in the table? On pressing, a little notification saying `"Code copied to clipboard"`, or something like that?

**Comment by wlthomson** [comment]
@wlthomson is on it!
