### ISSUE TITLE
Presentation entities not displaying correctly

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/unified-codes#313]
If an item is coded at level UC7 (presentation) then it does not display correctly, viz:

![Screen Shot 2021-02-15 at 6 12 20 PM](https://user-images.githubusercontent.com/9192912/107907805-853e0800-6fb9-11eb-963f-fd3442e14e3f.png)

This compares with the current live site:

![Screen Shot 2021-02-15 at 6 12 31 PM](https://user-images.githubusercontent.com/9192912/107907815-8d964300-6fb9-11eb-83f6-b0e988460213.png)

## Expected Behaviour
The items at UC7 should display, with the presentation in the name. In the above example the strength is `20mg per   mL` with a presentation of `240mL`

Would suggest a title of `Abacavir Solution 20mg per mL` for the UC6 level item ( which currently doesn't appear to show? ) and somewhere indicating available presentations, listing the `240mL`

**Comment by wlthomson** [comment]
@mark-prins I can look into this if still an existing issue?

**Comment by mark-prins** [comment]
Thanks @wlthomson - yes please!

**Comment by katherine-sussol** [comment]
Fixed by https://github.com/openmsupply/unified-codes/pull/367
![image](https://user-images.githubusercontent.com/65875762/118432021-b13d6680-b72b-11eb-8fad-367de7053452.png)
