### ISSUE TITLE
Synonyms are not displayed

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/unified-codes#314]
Currently synonyms are neither imported nor displayed

## Expected Behaviour
List the synonyms somewhere.
Search synonym values as well as the current description

**Comment by DhanyaHerath** [comment]
Duplicate of https://github.com/openmsupply/unified-codes/issues/339

**Comment by mark-prins** [comment]
> Duplicate of #339

But that one is about 'common names' and this one is for 'synonyms' and those are.. oh, wait.
