### ISSUE TITLE
Live server giving errors to requests from postman and msupply

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/unified-codes#318]
## Expected Behaviour
mSupply item input search for codes should work. So should the postman collections in this repo/wiki.

## Current Behaviour
In mSupply when I search, it returns no results. If I debug msupply, it's the api is returning errors. When I use the postman collection provided in the wiki, it also returns the same errors for all saved requests. For example:

```JSON
// Get Product by Code
{
    "errors": [
        {
            "message": "Cannot read property 'properties' of undefined",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "entity"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ],
    "data": null
}
```

## Possible Solution

I tried use https rather than http as given by the links in the repo wiki. This did not help.

## Steps to Reproduce (bugs only, delete if not applicable)

1. Download collection
2. create environment variable `GraphQLHost` and give live url provided: http://codes.msupply.foundation:2048
 (both source from repo wiki)
3. Test the requests in the collection
4. Get errors

**Comment by Chris-Petty** [comment]
I've wondered if it's something to do with our office, but can't quite test it. The webpage works fine 🤷

**Comment by mark-prins** [comment]
I'd updated the server and the `entities` query had a bug in it. Is working now.

**Comment by Chris-Petty** [comment]
Woo, can confirm is working from msupply 😃 . Thanks
![image](https://user-images.githubusercontent.com/7684221/108801677-34eb2980-75fb-11eb-8062-e6870a2bd1b3.png)

**Comment by katherine-sussol** [comment]
Postman collection was also out of date, oops! Has been updated with the newest requests too (to aid future testing).
