### ISSUE TITLE
Convert existing v1 API to typescript

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#32]
Some bugs have already come up with the API, most of which would have been caught by the typescript compiler (e.g. #22). Migrating the existing code to typescript isn't a big undertaking, and I think it's a worth while trade-off in terms of time saved tracking down bugs over the lifetime of the app (also a good chance to expose some of the team to typescript). 

@mark-prins @katherine-sussol Thoughts?

**Comment by katherine-sussol** [comment]
I'm all for using TypeScript (for both selfish and usefulness reasons). Am an advocate of dev testing/catching errors ASAP in the workflow too 😺

**Comment by mark-prins** [comment]
![](https://media1.giphy.com/media/bKnEnd65zqxfq/giphy.gif)

**Comment by wlthomson** [comment]
![wink](https://user-images.githubusercontent.com/43223637/86904492-e7ea3e00-c164-11ea-9cbf-24724c41c048.gif)

**Comment by wlthomson** [comment]
![worky](https://user-images.githubusercontent.com/43223637/86905347-0c92e580-c166-11ea-9bb0-11a1aa888517.gif)
