### ISSUE TITLE
Missing product codes

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/unified-codes#330]
Migrated from https://github.com/sussol/universal-drug-codes-server/issues/66

The codes that are listed at product level are not listed at the item level. The WHO EML codes seem to list both the product and item codes (see https://github.com/sussol/universal-drug-codes-server/issues/64). But the RxNav and the UNSPSC does not seem to display. Likewise the NZULM seems to only give the item code (there is also a product code).

I am not sure if it is better to show all (with differentiation to make sure it is clear which is which) or only the item - but it should be consistent.

This should also be considered for ATC and DDD which seem to be at the product level.....

**Comment by DhanyaHerath** [comment]
Duplicate of https://github.com/openmsupply/unified-codes/issues/343
