### ISSUE TITLE
Drug interactions - Severity

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/unified-codes#342]
Migrated from https://github.com/sussol/universal-drug-codes-server/issues/53

None of the items that I have looked up have a severity recorded.  They all have N/A which I guess is not available (although at first I thought was not applicable).  
![image](https://user-images.githubusercontent.com/71358001/106968540-f0176400-67ad-11eb-90c1-4c0c6748182d.png)

I am wondering if this is still under development (in which case approx delivery date please), if it is just not really available, or if it is an error?

Currently the  only high severity checkbox is pointless.  Is it possible to have this unchecked by default (at least while the severity is not available)?

Thanks :-)

**Comment by katherine-sussol** [comment]
This is because one of the data sources for interactions (DrugBank) doesn't have any severity information available for drug interactions. In this case, Amox doesn't have any known high severity interactions.

There aren't many, but there are certain drugs do have high severity interactions that show up when the 'Only high severity' checkbox is selected, e.g. 
- Azathioprine 50mg tablet (3723a4bf)
- Azithromycin 250mg capsule (373ad4bf)

**Comment by mark-prins** [comment]
Not an issue, I think: due to data
