### ISSUE TITLE
Product details heading doesn't make sense

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/unified-codes#344]
## Expected Behaviour

When drilling down in the web UI to view a product, the descriptions on the page should be clear and easy to understand.

## Current Behaviour

Example header for Amoxicillin Oral Capsule 250mg:
![image](https://user-images.githubusercontent.com/65875762/111392119-d22d0f80-871a-11eb-8c4e-f772596b3569.png)

## Possible Solution

If possible I think it would be good to display the product hierarchy, something like Amoxicillin / Oral / Capsule / 250mg

## Steps to Reproduce (bugs only, delete if not applicable)

1. Open UC web (https://codes.msupply.foundation/) and search for a drug e.g. Amoxicillin
2. Click on a Drug 
3. Select 'Forms' and expand the tree as far as possible
4. Select a product at the lowest level
5. Inspect UI

**Comment by wlthomson** [comment]
I think this is a good issue for the changes we discussed (@katherine-sussol, @mark-prins):

- Update `DetailPage` to be consistently recursive (include type groupings in child lists, e.g. `"Routes"`, `"Forms"` etc.).
- Remove `DetailProduct` and migrate all functionality to `DetailPage` (including code copying, navigation etc.). 
- Update header to only display product category (not `type`).

Note: migrating navigation is a bit more work and isn't as high priority, so might leave this for a dedicated issue. Basic idea is to always navigate to the parent product, but expand the list to the entity with the relevant code).

**Comment by katherine-sussol** [comment]
Sounds good - I think this approach will fix #353 as well! 

Two birds, one scone? 😸

**Comment by Chris-Petty** [comment]
I know this is like a year or 2 after the discussion I should say this, but what are the chances of having a table like:

| Generic Name (copyToClipBoard) | Code (copyToClipBoard) | Parent | Form | maybe Another |?

9/10 times people are trying to track down an appropriate generic name and universal code (this brought to you by the market research of pulling stuff out of...). The other 1/10 is for a parent or some other grouping for reporting.

You could do Parent as first column, but if you're sorting alphabetically generic name then you'll probably group by parent naturally anyway.

**Comment by wlthomson** [comment]
> 
> 
> I know this is like a year or 2 after the discussion I should say this, but what are the chances of having a table like:
> 
> | Generic Name (copyToClipBoard) | Code (copyToClipBoard) | Parent | Form | maybe Another |?
> 
> 9/10 times people are trying to track down an appropriate generic name and universal code (this brought to you by the market research of pulling stuff out of...). The other 1/10 is for a parent or some other grouping for reporting.
> 
> You could do Parent as first column, but if you're sorting alphabetically generic name then you'll probably group by parent naturally anyway.

Right now focus is on getting existing functionality working, so don't really want to start making changes before fixing what we have. Also, note that this is just the header (the page has an expandable list below which can be used to explore the children and properties for the entity). I agree with the idea of being able to explore the parents as well as children, but at this point I think that comes under new functionality rather than a patch release!

**Comment by wlthomson** [comment]
My thinking on this one is to add some pre-processing to the data such that every entity has a `description` and a new field `fullDescription` (where `fullDescription` is defined recursively). E.g.:

```
{
  fullDescription: 'Amoxicillin 20mg',
  description: '20 mg',
  ,,,
}
```

**Comment by Chris-Petty** [comment]
> > I know this is like a year or 2 after the discussion I should say this, but what are the chances of having a table like:
> > | Generic Name (copyToClipBoard) | Code (copyToClipBoard) | Parent | Form | maybe Another |?
> > 9/10 times people are trying to track down an appropriate generic name and universal code (this brought to you by the market research of pulling stuff out of...). The other 1/10 is for a parent or some other grouping for reporting.
> > You could do Parent as first column, but if you're sorting alphabetically generic name then you'll probably group by parent naturally anyway.
> 
> Right now focus is on getting existing functionality working, so don't really want to start making changes before fixing what we have. Also, note that this is just the header (the page has an expandable list below which can be used to explore the children and properties for the entity). I agree with the idea of being able to explore the parents as well as children, but at this point I think that comes under new functionality rather than a patch release!

Yea absolutely, I was just putting somewhere
