### ISSUE TITLE
Need copy to clipboard at nested levels wherever there is a code

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/unified-codes#366]
## Expected Behaviour
At the top level there is a copy to clipboard icon by the code:
![image](https://user-images.githubusercontent.com/7684221/112415699-25d9d180-8d89-11eb-8851-5d9031c19931.png)

If you go digging for the lowest level (not sure if to call it that), there is no copy to clipboard icon. In fact you can't highlight and copy it either - each row is a button that takes you back to the top level drug (I reckon you'd be fine to not do that at all!):
![image](https://user-images.githubusercontent.com/7684221/112415587-ee6b2500-8d88-11eb-988e-e1942c3faf1e.png)

I just realised it doesn't take you to the top level:

![image](https://user-images.githubusercontent.com/7684221/112416303-49514c00-8d8a-11eb-89fb-1c48069c8c50.png)

I got confused. Maybe that's what https://github.com/openmsupply/unified-codes/issues/344 is about though 😃 . You can copy it from the place above, but trying to make this a streamlined resource for copy pasta of codes.

## Current Behaviour

The current behaviour it's hard to copy/paste codes for medicines (at the lowest level that would be prescribed/stock managed). I'd argue this is the most common use case we'll have for browsing this web site.

## Possible Solution

Make a copy paste button standard everywhere there is a code. If I may... could even make it a standard react component used where evs there is a code `<UniversalCode code={theCode} />` 😃

**Comment by wlthomson** [comment]
This will be covered by the changes introduced to fix #344. Will leave open for now and add to the PR description.

**Comment by wlthomson** [comment]
This will be covered by the changes introduced to fix #344. Will leave this issue open to be referenced as one of the issues fixed by the PR when it comes in 👍 .

**Comment by katherine-sussol** [comment]
Fixed with #367 🥳  (no fancy tablet/liquid icons anymore, cos they were replaced with more useful but less fancy clipboard icons?)
