### ISSUE TITLE
Sinopharm COVID19 vaccine missing from mSupply

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/unified-codes#392]
From https://support.msupply.org.nz/cerb6/profiles/ticket/TH-5195-TJ

## Expected Behaviour

Vaccine should show up in mSupply when trying to assign a UCS

## Current Behaviour

It's not showing up

## Possible Solution

Data loader skips uc7 if there is a qualifier but no strength. Should be updated

## Steps to Reproduce (bugs only, delete if not applicable)

1. Log into mSupply -> Item -> Show Items -> Find -> Pick and Item and try to assign a UCS
2. Search for 'COV' in the UI and try to find Sinopharm vaccine

**Comment by mark-prins** [comment]
side note: why, oh why, aren't the variables renamed in the `DataParser`? Every line which has uc4, uc7 etc has a comment explaining what these are. If it was important to keep uc4 then `uc4_doseForm` but just `doseForm` would mean that we don't have to explain every line.
