### ISSUE TITLE
Add external product lookup capability to GraphQL API

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/unified-codes#41]
## Expected Behavior

- When a GraphQL API request is made for an existing product, the GraphQL API should have the ability to return data from external sources, e.g
  - Drug Interactions (from https://rxnav.nlm.nih.gov/REST/interaction/interaction.json?rxcui=[rxcuid])
  - Drugbank details/image (from https://www.drugbank.ca/drugs/[DBID])

## Current Behavior

Not implemented yet.

## Possible Solution

- Add new query for interactions by universal code
  - Add custom resolvers in Apollo GraphQL Layer to first perform internal lookup for rxcui code, then perform external lookup against rxnav
    - (Possible enhancement) Search up/down Dgraph product hierarchy for closest matching RxCui 
- Update GraphQL schema to return external codes/urls as part of responses when returning medicinal product info

Sample drug interaction response:
- Sample response
[sampleInteractionResponse.json.zip](https://github.com/openmsupply/unified-codes/files/4935122/sampleInteractionResponse.json.zip)

Update: After discussion with Craig - we will return the whole RxNav payload as a string and let mSupply handle the display (idea being that it will be stored in mSupply and synced out to all sites). No requirement to show interactions in our Web UI as it's main benefit is the mSupply use.

**Comment by wlthomson** [comment]
@katherine-sussol I think this should probably be left until next weeks sprint?

**Comment by katherine-sussol** [comment]
Have some spare capacity so happy to get started on it this week - we can roll it over to target end of next sprint if we find that by end of tomorrow that it's not yet done (which is most likely what will happen).

**Comment by katherine-sussol** [comment]
@wlthomson @mark-prins Wanting to get your guy's ideas on the possible solution for this one (we can also discuss it next week while planning the next sprint if this works better). It seems a lot of Dgraph's GraphQL functionality is still under development, e.g. things like custom resolvers and auth directives are not officially supported until 20.07.0. How do we feel about using features still in beta? Were there other GraphQL provider we had in mind as alternatives?

I'm also not a fan of routing GraphQL requests through our REST api since right now it's more of a necessary thing in place for backward compatibility that we eventually want to get rid of, but I think we could make it work that way if needed.

**Comment by katherine-sussol** [comment]
Currently Blocked by #52
