### ISSUE TITLE
Implement Product Lookup in Web UI

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/unified-codes#5]
### Description
Part of #10 

### Goal
Allow end users to browse drugs/products through the web UI

### Requirements
- A web UI to lookup codes (don’t need to replicate or support the v1 web UI)
- Ability to filter by default to show drugs only (with a UI switch to be able to view all, including things like 'tents')

### Current Discussion Points/Agreements
- Not required for #2

**Comment by wlthomson** [comment]
Sorry, I might have duplicated this a bit with #10!

Could migrate this into #10 and update this issue to just be for one core web UI feature that you think is the best place to start (my thinking is something like the lookup)?

**Comment by katherine-sussol** [comment]
Oh whoops. Yeah we can do that, will update.

**Comment by katherine-sussol** [comment]
@wlthomson I've condensed this one down into just an issue for the lookup, can add the bit about admin and all the requirements into #10

**Comment by wlthomson** [comment]
Closing as outdated 🎉 .
