### ISSUE TITLE
Refactor repo as nx monorepo

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#58]
Idea of this issue is to get a discussion going and decide how we might want to organise are project in a way that makes managing our front-end and multiple back-end dependencies a bit easier.

## Expected Behavior

Some of the things I think we could benefit from:

- Shared dev configs (prettier, babel, typescript, etc.)
- Shared types (e.g. shared interfaces/schemas for consistency between front-end and back-end services).
- Shared data (e.g. data for populating back-end can also be used by front-end as test fixtures).
- End-to-end (E2E) testing (e.g. test services working together to replicate functionality in the wild).
- Easier scalability (e.g. if we decided to separate the admin portal out as a separate web app, this would be made easy with shared components etc.).

## Current Behavior

Currently we manage all our projects separately. This has already been a bit tricky (e.g. setting up tests), and I think this could get a bit messy as we scale. Thinking is that we could benefit a lot from having some tools to speed things up and to keep things nice and tidy (would also be a good chance to research monorepo toolkits for omsupply).

## Possible Solution

A few possible options:

- [bazel](https://bazel.build/).
- [baur](https://github.com/simplesurance/baur).
- [buck](https://buck.build/).
- [lerna](https://lerna.js.org/).
- [nx](https://nx.dev/).
- [pants](https://www.pantsbuild.org/).

Of these, `nx` stands out to me as the most comprehensive and best documented... but feedback welcome!

**Comment by wlthomson** [comment]
@mark-prins @katherine-sussol Any thoughts?

**Comment by katherine-sussol** [comment]
Initial thoughts:
Have had an initial look at nx and created a sample workspace.

Default structure (created with nx CLI commands) looks a bit like this:
```
<workspace_name>\
  apps\
    app1\
      src\
          app\
            file1.ts
            file2.ts
          assets\
          environments\
    app2\
      src\
          app\
          assets\
          environments\
  libs\
  dist\
    <transpiled versions of apps>
  tools\
```

For initial refactor, current thinking/approach is just grabbing everything we currently have as a 'folder' under unified-codes and adding it as an app in the nx workspace (using `nx generate`)
E.g
- api (using [@nrwl/node](https://www.npmjs.com/package/@nrwl/node))
- data-service (using [@nrwl/node](https://www.npmjs.com/package/@nrwl/node))
- web (using [@nrwl/react](https://www.npmjs.com/package/@nrwl/react))

These plugins have their own default builder commands for building/testing/linting/serving applications (replacing the existing npm scripts we have per project).
E.g for api:
- `nx build api`
- `nx serve api`
- `nx test api`

**Comment by wlthomson** [comment]
@katherine-sussol Nice! 

Don't have much to add, just to mention that we will also need to add `auth-service` (using @nrwl/node), which is currently under `data-service`.
