### ISSUE TITLE
Centralise hardcoded urls and settings

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/unified-codes#59]
## Expected Behavior

Centralised location for env specific settings.

## Current Behavior

There are several configs and settings that are currently hardcoded into the application
e.g.
- api/src/handlers.js
  - `const dgraphClient = new DgraphClient(new DgraphClientStub('http://localhost:8080'));`
- dgraph/graphql/src/data.js
  - `this.baseURL = 'http://localhost:8080';`

## Possible Solution

- Move to constants file or .env

**Comment by wlthomson** [comment]
I think at this stage having hostnames/paths etc. hardcoded is OK, but I agree with moving them to a `.env` file at some point. I think this is probably a subtask of or duplicate of #58?

**Comment by katherine-sussol** [comment]
Yeah, I agree, not a rush, just didn't want to lose track of it :). I also think it's a likely candidate to be done after (or as a subtask) of #58? (actually think either works, as long as we don't do it beforehand to avoid duplicating work 😄 ).

**Comment by katherine-sussol** [comment]
Looks like these changes have snuck in under a few various different PRs. Will close this one now.
