### ISSUE TITLE
Authorisation/access control by the Dgraph server

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/unified-codes#6]
### Description
Placeholder issue to discuss/plan out how to implement access control for the Dgraph server.

### Goal
Secure the server against unauthorised transactions (e.g. non admins should not be able to modify the schema or alter data). 

### Scope
- Restrict access to modify schema or data via external API

Initial thoughts (from comments):
- Public Access (read only)
- Admin Access (read + write)

**Comment by wlthomson** [comment]
I think maybe this issue could be updated to just be for the API? Just because of the way the epics are structured (sorry!), it would make it easier to categorise! I think most likely that the authentication logic for the UI will probably fall back on the API (or dgraph authentication if we are at that stage).

@katherine-sussol Thoughts?

**Comment by katherine-sussol** [comment]
Hm, in my mind this depends if we want to include it in the MVP. Do we want to be able to demonstrate that we can secure Dgraph mutations against unauthorised users 🤔 ? If so then we should update this one.

Otherwise I'd be inclined to leave it up for discussion after we've done MVP.

**Comment by mark-prins** [comment]
I was hoping to push it out until after MVP - but I agree with your thought @katherine-sussol - that we should demonstrate securing Dgraph mutations.

**Comment by wlthomson** [comment]
Maybe some confusion from me not being very clear!

I think we definitely need to show authorisation in the MVP, but my thinking here is that this issue might be a bit too broad. From my perspective, I think there are three issues here:

1. Authorisation/access control by REST server.
2. Authorisation/access control by the Dgraph server.
3. Authorisation/access control by the web server.

I think the first two probably need to be included in the MVP (ideally, the REST server authorisation would work in the same way as the other endpoints, i.e. just be a layer over the top of the graph authorisation, but initially we might have to implement it in both places). I think the web server authorisation can wait.

My suggestion above was to update this issue to be more explicitly targeted at the API (and not the web server). Should have been more clear that I think this should be included in the REST server in the MVP.

I think the example doesn't need to be sophisticated. Probably just using a JWT token or something similar with maybe a concept of a user and an admin (user can read, admin can read+write)?

@katherine-sussol @mark-prins Thoughts?

**Comment by mark-prins** [comment]
The brief is to maintain the current REST implementation, to support existing clients.
That has no auth on it - so we don't need to implement *any* auth in the REST API.

Agree that for the MVP, the key part is 2. above - I'm fairly confident that we'll be able to knock up a web server authentication implementation. The point of uncertainty is around Dgraph.
Sounds to me that splitting the issue up would be wise - thanks @wlthomson!

**Comment by katherine-sussol** [comment]
I've updated the issue to be more narrowly scoped, and will create a separate one for the web server authentication - thanks both! 

I agree with @wlthomson that for MVP a simple example to show concept of user/admin sounds good. For later implementation might we want to split it up further into public/users/admin? E.g.
- Public (read only)
- User (can read and make new drug submission suggestions)
- Admin (can read, and approve/make new drug submissions)

**Comment by katherine-sussol** [comment]
I think this issue is no longer needed as we now have #66 - will close and tag as duplicate (will still be in the closed issues for reference purposes!)
