### ISSUE TITLE
Include 3rd party disclaimers in application 

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/unified-codes#64]
[Placeholder issue to track/ensure we do this before public release]

- NLM requests users of the API to provide the following statement in consuming applications:
  - "This product uses publicly available data from the U.S. National Library of Medicine (NLM), National Institutes of Health, Department of Health and Human Services; NLM is not responsible for the product and does not endorse or recommend this or any other product." 

... any additional external licenses/disclaimers to be added as we find them

## Possible Solution

- Add to GraphQL responses?
- Display in Web UI?

**Comment by DhanyaHerath** [comment]
bumping because I'm emailing Rx Nav at the moment and feel bad that we don't have their disclaimer :D 
I think it should definitely display at least in the About page of the web UI, and maybe also [here](https://github.com/openmsupply/unified-codes/wiki) since the `API` button links there?

**Comment by katherine-sussol** [comment]
Snuck in wiki update. Tiny PR created to add the disclaimer to the bottom of the About page.

**Comment by katherine-sussol** [comment]
Pushed About page change to the live server (no other updates done except this one) 🤫

**Comment by DhanyaHerath** [comment]
Yay! Amazing thanks @katherine-sussol :D
