### ISSUE TITLE
Add frontend authorisation logic

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/unified-codes#76]
Authorisation logic to secure areas of the web app and authenticate against supplied credentials.

## Expected Behaviour
Should be prevented from accessing certain areas of the site.
Should be able to login using correct credentials.
Prevented from logging in using incorrect credentials.
Once authenticated, should be able to access restricted areas of the site.

**Comment by wlthomson** [comment]
I agree with everything in this issue, but I think it's almost more of an epic! Might be better to break it up a bit by giving each of the tasks in the description their own issue? I think an issue each for authentication (e.g. credential validation + token) and authorisation (e.g.  token validation) would be sufficient! 

I think logic is sufficient here, think we can roll the UI components separately (they're pretty simple). I think we will also need to have a discussion on how we plan to manage browser state (e.g. do we need to use context or redux etc, or can the browser manage this for us).

**Comment by wlthomson** [comment]
Closing out but leaving myself a reminder to make issues for the tasks in the description!

@wlthomson.
