### ISSUE TITLE
Upgrade mSupply to use drug interactions from universal code server

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/unified-codes#8]
### Description
Placeholder issue to discuss/plan out how we will manage drug interaction data both in the Universal Codes application and within mSupply.

### Goal
Consensus on approach. This will form the basis for separate sub-issues to build it out.

### Requirements
- Ability to look up drug interactions from NIH 

### Current Discussion Points/Agreements
- Not required for #2
- Might need to cache data in desktop?
  - Version data with integer value?

**Comment by wlthomson** [comment]
I think could possibly split this out into two separate issues?

1. add drug interaction data to schema.
2. add mSupply functionality for looking up interactions from universal codes server.

My thinking is the last one would probably be better on the mSupply repo, although will probably also need an issue here for discussion on how we expose the interactions data to mSupply, e.g. do we extend the `v1` API or update mSupply to use new graphql types? 

@katherine-sussol @mark-prins Thoughts?

**Comment by wlthomson** [comment]
I think might be good idea to keep this parked until we have a bit more of an idea of how we want to approach mSupply integration in general. I think the scope is big enough to justify a discussion epic (at this stage will hold off on a project board, but will probably be useful). 

Discussion epic is [here](#92). Will update with research so far and my current thoughts.

![work_2](https://user-images.githubusercontent.com/43223637/88754194-2302ee80-d1b2-11ea-8af2-274239b2ca36.gif)

**Comment by katherine-sussol** [comment]
Hmm, this issue seems redundant now as it has been superseded by several other issues already (https://github.com/sussol/msupply/issues/6974 in particular) - as such, I am going to close it 🔐
