### ISSUE TITLE
Dockerise services

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/unified-codes#99]
As discussed in Sprint 4 meeting (#69) 

## Possible Solution

- Create dockerfile for each separate service in the nx repo (recommended best practice)
  - legacy-api
  - data-service
  - web
- Scripts to individually build docker images
- Scripts to individually run docker images
- Create Docker compose file to start/run all aforementioned services

Future:
- Scripts to run dgraph zero/alpha/ui in separate docker containers (https://dgraph.io/docs/deploy/single-host-setup/ probably enough?)
- Set up docker builds on git push (to master) and publish to dockerhub?

**Comment by katherine-sussol** [comment]
Just creating this issue today - did not get a chance to look at this last week

**Comment by wlthomson** [comment]
Bumped to week 5.

**Comment by wlthomson** [comment]
Fixed by #135.
